### ISSUE TITLE
Set enough memory so rebuilding repository is not triggered

### ISSUE THREAD

**Issue by oplatek** [UFAL-DSG/alex#34]
```
frame_in of 290304 frames
Forward decoding of 1808 frames in 24.98 secs
```

LOG (PyGmmLatgenWrapper:RebuildRepository():determinize-lattice-pruned.cc:285) Rebuilding repository.
LOG (PyGmmLatgenWrapper:RebuildRepository():determinize-lattice-pruned.cc:285) Rebuilding repository.
LOG (PyGmmLatgenWrapper:RebuildRepository():determinize-lattice-pruned.cc:285) Rebuilding repository.
LOG (PyGmmLatgenWrapper:RebuildRepository():determinize-lattice-pruned.cc:285) Rebuilding repository.
hyp_out: get_lattice+nbest in 39.75 secs

```
frame_in of 62720 frames
Forward decoding of 386 frames in 1.63 secs
hyp_out: get_lattice+nbest in 0.09 secs
```

Decoded indomain_data/aotb_prototype_total/part1/2013-06-26-23-21-33.575903-CEST-604607376/vad-2013-06-26-23-22-28.331316.wav
reference ZE ZASTÁVKY LAUROVÁ DO NÁDRAŽÍ VRŠOVICE
decoded _NOISE_ ZE ZASTÁVKY LAUROVÁ NÁDRAŽÍ VRŠOVICE

**Comment by etienne1985** [comment]
Hi,
I'm getting a similar issue... I was getting slowdown, "Rebuilding repository" and dropped words. By increasing the mem-max like you recommended I got rid of the "Rebuilding repository", but it's still slow and more significantly, stretches of words get dropped around those points. This is with straight Kaldi, no python. Any ideas what's causing this? Thank you in advance!

**Comment by oplatek** [comment]
Hi @etienne1985 ,
Can you be more specific for "stretches of words get dropped around those points"?
For clarification, are you using the onl-rec code or just plain Kaldi?
